### ISSUE TITLE
Cannot find the solution file

### ISSUE THREAD

**Issue by maerger** [Panbaa/PCF-MDA-Backgroundcontroll-for-Multiline-Textfields#1]

**Comment by r0man5k** [comment]
yeah, i cant find it either.

**Comment by FredAlainCodjia** [comment]
Hello,
Cannot find the solution neither, if someone got it I am very interested

**Comment by Panbaa** [comment]
Hey Everybody, the Solution is not provided in my Files. Its just the plain Code so everybody can download and work with it, then generate their own Solutions. I recomend using the XrmToolBox for that part :D happy coding

**Comment by FredAlainCodjia** [comment]
Thank you for your answer @Panbaa ! I will ask a dev to package it. In the meantime if anyone package it, I would be happy to get it :)

**Comment by roman5k** [comment]
Hello Panbaa,

cant u just add a solution zip file. it would be very appreciated. also, i think
if you want your solution to be used, then i think this would make it a lot 
easier for a lot of low code developers.

thanks in advance!

regards, 

roman

**Comment by Panbaa** [comment]
Added it here MultilineColorChange/Solution/bin/Release.

**Comment by roman5k** [comment]
awesome, many thanks!!

**Comment by roman5k** [comment]
actually, for me the solution zip is not working. i imported it,
but it wont show up as an option in the form...

**Comment by Panbaa** [comment]
did you put it on a text-area-field?

**Comment by roman5k** [comment]
yes, i tried to put it on a text area field!
but the option wouldnt show up
